import { StoreProvider } from "@/redux/StoreProvider";
import TopLayout from "@/shared/layout/layout";
import { Metadata } from "next";
import './globals.css'
export const metadata: Metadata = {
    title: {
        default: "Next.js",
        template: "%s | By Arun Sharma",
    },
    description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <StoreProvider>
                <body>
                    <main className="bg-red">
                        <TopLayout>{children}</TopLayout>
                    </main>
                </body>
            </StoreProvider>
        </html>
    )
}