import { StoreProvider } from "@/redux/StoreProvider";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: {
        default: "Next.js",
        template: "%s | By Arun Sharma",
    },
    description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <StoreProvider>
                    <main style={{ display: 'flex', gap: '20px' }}>
                        <header>Sidebar</header>
                        {children}
                    </main>
                </StoreProvider>
                <footer>Footer</footer>
            </body>
        </html>
    )
}