import { Metadata } from "next";

export const metadata: Metadata = {
    title: {
        default: "Next.js",
        template: "%s | By Arun Sharma",
    },
    description: "Generated by Next.js",
};
//template re-render the pages or routes , present in layout
export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <main style={{ display: 'flex', gap: '20px' }}>
                    <header>Sidebar</header>
                    {children}
                </main>
                <footer>Footer</footer>
            </body>
        </html>
    )
}